export const GENERATE_ORDER_REQUEST = 'GENERATE_ORDER_REQUEST'
export const GENERATE_ORDER_SUCCESS = 'GENERATE_ORDER_SUCCESS'
export const GENERATE_ORDER_FAIL = 'GENERATE_ORDER_FAIL'

export const ORDER_HISTORY_REQUEST = 'ORDER_HISTORY_REQUEST'
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS'
export const ORDER_HISTORY_FAIL = 'ORDER_HISTORY_FAIL'

export const A_ORDER_REQUEST = 'A_ORDER_REQUEST'
export const A_ORDER_SUCCESS = 'A_ORDER_SUCCESS'
export const A_ORDER_FAIL = 'A_ORDER_FAIL'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const UPDATE_ORDER_REQUEST = 'EDIT_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS'
export const UPDATE_ORDER_FAIL = 'EDIT_ORDER_FAIL'
export const UPDATE_ORDER_RESET = 'EDIT_ORDER_RESET'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL'
export const DELETE_ORDER_RESET = 'DELETE_ORDER_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'